version: '3'

services:
  app-lastro-btc:
    build:
      context: ./vendor/laravel/sail/runtimes/8.1
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP-1000}'
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'
    volumes:
      - .:/var/www/html
    environment:
        WWWUSER: '${WWWUSER-1000}'
        LARAVEL_SAIL: 1
    expose:
      - 80
    ports:
      - "80:80"
    restart: unless-stopped
    command: php -d variables_order=EGPCS /var/www/html/artisan serve --host 0.0.0.0  --port 80
    networks:
      - default

    depends_on:
      - postgres-lastro-btc
      - redis-lastro-btc

  postgres-lastro-btc:
    image: postgres:13
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: '${DB_DATABASE-lastro_db}'
      POSTGRES_USER: '${DB_USERNAME-lastro_btc}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  redis-lastro-btc:
    image: redis:alpine
    ports: 
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD-1234}


